package main

import (
	crand "crypto/rand"
	"fmt"
	"io"
	"math/rand"
	"time"
)

func genPassword(minLength int, maxLength int) string {
	var chars = []byte("ABCDEFGHIJKLMNOPQRSTUWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_=+,.?/:;{}[]`~")

	var length = rand.Intn(maxLength - minLength) + minLength

	newPassword := make([]byte, length)
	randomData := make([]byte, length + (length / 4))
	clen := byte(len(chars))
	maxrb := byte(256 - (256 % len(chars)))
	i := 0
	for {
		if _, err := io.ReadFull(crand.Reader, randomData); err != nil {
			panic(err)
		}
		for _, c := range randomData {
			if c >= maxrb {
				continue
			}
			newPassword[i] = chars[c % clen]
			i++
			if i == length {
				return string(newPassword)
			}
		}
	}
}

func main() {
	rand.Seed(time.Now().Unix())

	fmt.Print("Inform the minimum length, please: ")
	var minLength int
	fmt.Scanf("%d", &minLength)

	fmt.Print("Inform the maximum length, please: ")
	maxLength := 10
	fmt.Scanf("%d", &maxLength)

	fmt.Printf("This is your password generated by this Go program: %v\n", genPassword(minLength, maxLength))
}